apiVersion: v1
kind: Pod
metadata:
  name: insecure-hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: host-logs
          mountPath: /host/logs
          readOnly: true
  volumes:
    - name: host-logs
      hostPath:
        path: /var/log
        type: Directory
