apiVersion: v1
kind: Pod
metadata:
  name: secure-hostpath-pod-fixed
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - "ALL"
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: "RuntimeDefault"
      volumeMounts:
        - name: safe-data-storage
          mountPath: /data
  volumes:
    - name: safe-data-storage
      emptyDir: {}
